feat: 添加 autosize 功能
FEMessage/v-editor pull request #115
Opened 2020-08-26 09:11 UTC by shoyuf

## Why
需要一个 autosize 属性，让高度根据内容伸缩，目前每个用例统一设置高度，内容却只有一行，浪费了空间。

## How
可以设置 autosize 属性，autosize 为一个对象，内部有 minRows 和 maxRows
1. 当 autosize 属性不设置的情况下，和组件原逻辑一致
2. 当设置 autosize，将忽略设置的 height 属性

![yuque_diagram (1)](https://user-images.githubusercontent.com/27998490/91284835-03fe7900-e7bf-11ea-9d05-2b31507124f1.jpg)

## Docs
`/docs/autosize.md`

2020-08-26 10:01 UTC, colmugx approved these changes

2020-08-27 02:23 UTC, shoyuf commented on src/v-editor.vue
> +      const {minRows, maxRows} = this.autosize
需要测试：
1. 只设置一个值是否表现正常
2. 设置Infinity是否表现正常

2020-09-01 07:57 UTC, levy9527 requested changes
只设置一个值：minRows时，表现不正常。直接在netlify 可见

2020-09-02 08:05 UTC, levy9527 approved these changes

2020-09-02 11:32 UTC, levy9527 commented
有两个修改点：
1.
```
.ck.ck-editor__editable_inline>:last-child {
  margin-bottom: 8px;
}
```
2. autosize例子，minRows=3时，输入第三行时编辑器会变高，视觉上产生抖动。 则应再调整行高算法，让用户在输入的n行，n = minRows 时，编辑不会增加高度。

下面是 minRows = 3 时，最终效果图的高度，仅供参考
![image](https://user-images.githubusercontent.com/9384365/91976016-eac37280-ed52-11ea-9fb2-0319d2d7b25a.png)

2020-09-02 12:00 UTC, merged