revert: 回档`watch.value`相关代码
FEMessage/v-editor pull request #46
Opened 2019-09-18 11:34 UTC by eviIIt

## Why

- 出现的问题是无法异步赋值给 `v-bind:value`, 删掉相关代码的理由:
	-	一开始不聚焦编辑框, 就开始操作菜单(例如上传一张图片)
	-	再直接开始输入内容, 会使编辑框一直重新赋值.

相关代码为

https://github.com/FEMessage/v-editor/compare/dev...evillt-works:fix/revert-value-watcher?expand=1#diff-f1612288725bc8bc9b559eb263692dddR85

https://github.com/FEMessage/v-editor/compare/dev...evillt-works:fix/revert-value-watcher?expand=1#diff-f1612288725bc8bc9b559eb263692dddR98

## How

1. 回退 `watch.value`
2. 回退 `onfocus` 和 `onblur`

## Notice

正常操作应该是:

- 先让编辑器聚焦(手动)
- 方可正常操作

2019-09-18 11:58 UTC, colmugx approved these changes

2019-09-18 12:33 UTC, levy9527 commented on src/v-editor.vue
> +    // 详细注释以及解释可以参考 emitValue 行号大约为 236
236 行，能不能更精确。

2019-09-18 12:44 UTC, levy9527 commented on src/v-editor.vue
>      return {
点击toolbar的按钮，需要让 editor focus

2019-09-19 03:55 UTC, levy9527 commented on src/mixins/focusHack.js
> +const menuItemsStore = []
命名为 menuItems

2019-09-19 03:55 UTC, levy9527 commented on src/mixins/focusHack.js
> +    if (menuItemsStore.length) {
加注释：clearFocusHack

2019-09-19 03:56 UTC, levy9527 commented on src/mixins/focusHack.js
> +    initTextElementEvent() {
initFocusHack

2019-09-19 03:57 UTC, levy9527 requested changes

2019-09-19 03:57 UTC, levy9527 commented on src/mixins/focusHack.js
> +    addToolbarItemClickEvent(item) {
initToolbarItemFocusHack

2019-09-19 06:08 UTC, levy9527 approved these changes

2019-09-19 06:08 UTC, merged